version: "3.9"

services:
  db:
    image: postgres:15
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: Test123456
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U pgadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://pgadmin:Test123456@db:5432/portfolio?sslmode=disable
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && node dist/index.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
