export type TagInfo = { emoji: string; label: string; description: string };
export const TAG_GUIDE_FALLBACK: Record<string, TagInfo> = {
  "🔷": { emoji: "🔷", label: "Game Client", description: "게임 클라이언트 전반" },
  "🔴": { emoji: "🔴", label: "AI Development", description: "AI 개발 전반" },
  "🟣": { emoji: "🟣", label: "XR / Creative Tech", description: "VR/AR/그래픽/시네마틱" },
  "🟠": { emoji: "🟠", label: "Web / API Development", description: "웹/프론트/API/데이터 시각화" },
  "⚫": { emoji: "⚫", label: "Backend / Infra", description: "서버/DB/보안/네트워크" },
  "🟢": { emoji: "🟢", label: "Cloud / DevOps", description: "클라우드/CI/CD/컨테이너" },
  "🎮": { emoji: "🎮", label: "Gameplay", description: "스토리·전투·퀘스트·규칙 시스템" },
  "🕹": { emoji: "🕹", label: "Interaction", description: "입력·UI·오브젝트 상호작용" },
  "🎯": { emoji: "🎯", label: "Actor/Pawn AI", description: "FSM·BT·RL·경로 탐색" },
  "🗺": { emoji: "🗺", label: "Level/Scene", description: "씬 구성·오브젝트 배치·최적화" },
  "🗣": { emoji: "🗣", label: "NLP", description: "자연어 처리" },
  "📷": { emoji: "📷", label: "CV", description: "컴퓨터 비전" },
  "🖇": { emoji: "🖇", label: "Multimodal AI", description: "멀티모달 AI" },
  "🎨": { emoji: "🎨", label: "Generative AI", description: "생성형 AI" },
  "🤖": { emoji: "🤖", label: "Unified Intelligence", description: "AGI-like 시스템" },
  "🧠": { emoji: "🧠", label: "AGI Research", description: "단일모델 AGI 연구" },
  "🥽": { emoji: "🥽", label: "VR", description: "가상현실" },
  "📱": { emoji: "📱", label: "AR", description: "증강현실" },
  "🖌": { emoji: "🖌", label: "VFX/Graphics", description: "비주얼 이펙트/그래픽" },
  "🎬": { emoji: "🎬", label: "Cinematic", description: "시네마틱" },
  "🌐": { emoji: "🌐", label: "Frontend", description: "웹 프론트엔드" },
  "🔌": { emoji: "🔌", label: "API", description: "API 개발" },
  "📊": { emoji: "📊", label: "Data Viz", description: "데이터 시각화" },
  "🗄": { emoji: "🗄", label: "Database", description: "DB 설계/운영" },
  "🔒": { emoji: "🔒", label: "Security", description: "보안" },
  "⚡": { emoji: "⚡", label: "Realtime", description: "실시간 처리" },
  "📡": { emoji: "📡", label: "Networking", description: "네트워크" },
  "☁️": { emoji: "☁️", label: "Cloud", description: "클라우드" },
  "🔄": { emoji: "🔄", label: "CI/CD", description: "지속적 통합/배포" },
  "🐳": { emoji: "🐳", label: "Docker/K8s", description: "컨테이너/쿠버네티스" }
};
