name: Deploy Frontend & Backend to Azure

on:
  workflow_run:
    workflows: ["Provision Azure Infrastructure"]   # infra.yml의 name과 동일해야 함
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            workflows:
              - '.github/workflows/**'

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.workflows == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
      - run: |
          az webapp config container set \
            --name ${{ secrets.FRONTEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io
          az webapp restart \
            --name ${{ secrets.FRONTEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }}

  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true' || needs.changes.outputs.workflows == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest
      - run: |
          CONNECTION="postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_NAME }}.postgres.database.azure.com:5432/${{ secrets.POSTGRES_DB }}"
          az webapp config container set \
            --name ${{ secrets.BACKEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io
          az webapp config appsettings set \
            --name ${{ secrets.BACKEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --settings DATABASE_URL=$CONNECTION
          az webapp restart \
            --name ${{ secrets.BACKEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }}
