name: Provision Azure Infrastructure

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/main.bicep'
      - 'infra/infra-rg.bicep'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment sub create \
            --name main-${{ github.run_number }} \
            --location southeastasia \
            --template-file infra/main.bicep \
            --parameters \
              administratorLoginPassword="${{ secrets.POSTGRES_PASSWORD }}" \
              jwtSecret="${{ secrets.JWT_SECRET }}" \
            --debug
